---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    MY_VALUE: AgAyrdzRiPvcHpANUhYPCGbOSFEsQYvH4xDViSbHVZ86cf0GGnmrJu2TvORuhOWM638+2Gcw2k4cNKhbGtnKRENWTGWgAoRQ9x3kQ+OfoRsWDYyjyp+4Zv45CZTcVHBKDTzksFZpuL9rjMoZQvLVcAXflyJMYSsuOkrin9ItqWPLZztbHeV8p170APYE8EhSEAedi3AADPfy1YjRnswb5PCb48oeMtQvnyy39h04y3Xli8ne/p/xxqwPh8u69L2N8HRrvVGjp4cLPzfTkGlWACkYg0WPNM38zUqQocMT83xWdqCsUxipTriyMJo7xKIhRjadVECyTGOMHHpKO615++f6hCLt04mkq4pz180CpvCIwhZ19BwOWBBI4JqSUexFj4ioAZE2PLFQGb4mbMFJ8cZ32vXQV0uukkTYAXSxVHB5TT0BbXv8+DTf1n2A8HGd/kgf9ikB7Dwc7RrZhD2cG9JL7aP5ih5l12mAo+DtogUuMZWlAs+pJj6rKhbcWvNOGOW1NO+zbYeWZwZefZveCT3zbv8l7oGA3CE+Z26P3FhR1ZBD/bAnckaV/eKq2Edyr5u5G+j4nh3BvnE1UOwfZXHCSjMzGxiU9Q84TMUED6EUU0GDzxLzBE1skyODffOK0Xy+ULJ8FmFuRx1O29kmlxlG5nmnFpHDliboHeE8K066ygHHAmxu2slFI/T4mzImZsuzROfrO0dr2JHNLA==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
